project:
  type: book
  output-dir: _sites

navbar:
  background: primary
  search: true
  left:
    - text: "Home"
      href: index.qmd
    - text: "Preface"
      href: preface.qmd

book:
  title: "GEMV-Q"
  subtitle: "Matrix Vector Multiplication with Lattice-based Vector Quantization"
  reader-mode: true
  page-footer:
    left: |
      Under development.
    right: |
      This documentation was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://mlsquare.github.io/gemvq
  repo-url: https://github.com/mlsquare/gemvq
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - README.md
    - part: Lattices
      chapters:
        - docs/lattices/intro.qmd
        - docs/lattices/Z2.qmd
        - docs/lattices/A2.qmd
        - docs/lattices/D4.qmd
        - docs/lattices/E8.qmd
    - part: Quantizers
      chapters:
        - docs/quantizers/intro.qmd
        - docs/quantizers/Z2.qmd
        - docs/quantizers/hnlq.qmd
        - docs/quantizers/beta_selection_hnlq.qmd
    - part: GEMV-Q
      chapters:
        - docs/gemv/adaptive_matvec_approach.qmd
    - part: Notebooks
      chapters:
        -  docs/notebooks/nlq.ipynb
        -  docs/notebooks/hnlq_01.ipynb
        -  docs/notebooks/hnlq_02.ipynb
        -  docs/notebooks/hnlq_03.ipynb
    - part: Papers
      chapters:
        -  docs/papers/hnlq_paper.qmd
    - part: Drafts
      chapters:
        -  docs/lattices/intro_long.qmd


format:
  html:
    theme:
    - pulse
    - mlops.scss
    code-link: true
    author-meta: "mlsquare"
    callout-appearance: simple
    number-sections: false
editor: visual